trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  # Step 1: Checkout the code from the Git repository
  - checkout: self

  # Step 2: Set up .NET Core SDK
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.4.0' # Ensure this version aligns with your project requirements
      installationPath: $(Agent.ToolsDirectory)/dotnet

  # Step 3: Restore the dependencies
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Step 4: Build the application using MSBuild
  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'  # Assuming a solution file is present, otherwise target the csproj file
      msbuildArgs: '/p:Configuration=Release'
      clean: true

  # Step 5: Run Unit Tests
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'  # Update if you have test projects, otherwise you can remove this step

  # Step 6: Publish build artifacts for deployment
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  # Step 7: Deploy the application to Azure App Service
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Your_Azure_Subscription'
      appName: 'Your_App_Service_Name'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
